[unix_http_server]
file=/tmp/supervisor.sock  ; socket文件路径
chmod=0770                ; socket文件权限，770表示文件所有者和同组用户有 读/写/执行权限，其它用户无任何权限
chown=root:root       ; socket文件的所有者和组

[supervisord]
logfile=/dev/stdout              ; 主日志路径
logfile_maxbytes=0               ; 不限制日志大小(用完即弃无需考虑)
loglevel=info                    ; 日志等级
pidfile=/tmp/supervisord.pid     ; pid文件路径
nodaemon=true                    ; 设为true表示在前台运行(Docker前台)，方便Docker捕捉日志
minfds=1024                      ; 打开文件描述符的最小值
minprocs=200                     ; 最小进程数
autoshutdown=true                ; 所有服务停止后自动退出


[rpcinterface:supervisor]
; 启用supervisor的远程过程调用接口(RPC), 可以通过接口操控supervisor
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface


[supervisorctl]
; 告诉supervisorctl工具去哪里链接supervisord服务
serverurl=unix:///tmp/supervisor.sock


; FastAPI进程配置
[program:app]
command=/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
directory=/workspace
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME=/home/ubuntu
priority=50

